### ISSUE TITLE
Update to support GDAL 2.1?

### ISSUE THREAD

**Issue by robintw** [conda-forge/rasterio-feedstock#11]
The rasterio project itself (ie. the upstream codebase) supports GDAL 2.1 absolutely fine, but when I try to install rasterio from conda-forge it tries to downgrade GDAL for me:

```
The following NEW packages will be INSTALLED:

    affine:        2.0.0.post1-py35_0 
    click:         6.6-py35_0         
    click-plugins: 1.0.3-py35_0       
    cligj:         0.4.0-py35_0       
    expat:         2.1.0-1            
    giflib:        5.1.2-0            
    jasper:        1.900.1-2          
    json-c:        0.12-0             
    pyparsing:     2.1.4-py35_0       
    rasterio:      0.35.1-np111py35_1 
    snuggs:        1.3.1-py35_0       

The following packages will be DOWNGRADED:

    gdal:          2.1.0-np111py35_4 --> 1.11.4-np111py35_10
```

What's the best way to update this conda-forge package to support GDAL 2.1? Does it just need the `meta.yml` file editing to change the GDAL version number? Does GDAL even need to have a version number in there, as rasterio supports pretty-much all GDAL versions (except perhaps for insanely old ones).

**Comment by ocefpaf** [comment]
@robintw that was an "strategic" choice because people usually install `rasterio` together with `fiona` and `fiona` is not fully compatible with `gdal 2` yet.

If you want `rasterio` with `gdal 2` you can try the default channel version. We hope to remove the `gdal 1.11.x` pining for `rasterio` (and many others) as soon as `fiona` gets better support for `gdal 2`.

**Comment by robintw** [comment]
Ah ok, that makes sense.

Unfortunately, the most recent version of rasterio in the default channel is 0.25, whereas conda-forge has 0.35.1. Is there any way to get the default channel version updated?

**Comment by ocefpaf** [comment]
> Unfortunately, the most recent version of rasterio in the default channel is 0.25, whereas conda-forge has 0.35.1. Is there any way to get the default channel version updated?

Ping @msarahan :wink:

**Comment by sgillies** [comment]
@ocefpaf @robintw Fiona 1.7.0 is on PyPI now and supports either GDAL 1.x or 2.x. At last.

**Comment by robintw** [comment]
That's wonderful @sgillies - and perfect timing for getting things set up for one of my students!

(Just FYI, http://toblerity.org/fiona/ still shows docs for 1.4.0)

**Comment by ocefpaf** [comment]
@robintw `rasterio` is using `gdal 2.x` now (see #12). Thanks @sgillies :tada:
