### ISSUE TITLE
Rasterio 1.0.21 may need rebuild

### ISSUE THREAD

**Issue by djhoese** [conda-forge/rasterio-feedstock#115]
I've tried writing this issue 3 or so times now trying to figure out exactly what's going on. If I install rasterio in an existing environment (on OSX currently) I get 1.0.13. If I create a new environment (python=3.7 rasterio) then I get 1.0.21. If I go back to the existing environment and try to install rasterio=1.0.21 I get:

```
The following NEW packages will be INSTALLED:

  postgresql         conda-forge/osx-64::postgresql-10.6-ha1bbaa7_1000
  tzcode             conda-forge/osx-64::tzcode-2018g-h1de35cc_1001

The following packages will be UPDATED:

  libgdal               pkgs/main::libgdal-2.3.3-h0950a36_0 --> conda-forge::libgdal-2.4.0-h89caebc_1002
  rasterio                            1.0.13-py37h54a03ab_0 --> 1.0.21-py37h3683dd5_0

The following packages will be DOWNGRADED:

  cryptography                           2.5-py37hc2b1221_1 --> 2.5-py37hdbc3d79_1
  curl                                    7.64.0-heae2a1f_2 --> 7.64.0-heae2a1f_0
  krb5                                 1.16.3-hcfa6398_1001 --> 1.16.3-h24a3359_1000
  libcurl                                 7.64.0-he376013_2 --> 7.64.0-h76de61e_0
  libpq                                     11.2-h29c6f28_0 --> 10.6-hbe1e24e_1000
  libssh2                               1.8.0-hb1dc21d_1004 --> 1.8.0-hf30b1f0_1003
  openssl                                 1.1.1b-h1de35cc_1 --> 1.0.2r-h1de35cc_0
  python                                3.7.1-hbdd33cc_1002 --> 3.7.1-h145921a_1000

```

It seems that 1.0.21 has only been built for an older build of python (at least conda says "DOWNGRADE") or maybe openssl. Does this mean that 1.0.21 needs to be rebuilt?

**Comment by ocefpaf** [comment]
That may have to do with the current `openssl` migration, which is not over. I'm investigating...

**Comment by ocefpaf** [comment]
Ee have gdal with the new openssl, let's give this a try now.

**Comment by djhoese** [comment]
This looks to be fixed on my OSX machine. Although I have to admit I somehow missed me having the newest version already so now I'm not sure if this specifically fixed it or some other package build (when I ran `conda update rasterio` it updated other things but not rasterio).

**Comment by ocefpaf** [comment]
Hard to say. Because the openssl migration is still happening new combinations of packages are available every day. `libgdal` with latest openssl was built 2-days ago, so the GIS stack is starting to get rebuild and moving to the new one now.
