### ISSUE TITLE
libgdal repo archived

### ISSUE THREAD

**Issue by snowman2** [conda-forge/rasterio-feedstock#121]
https://github.com/conda-forge/rasterio-feedstock/blob/5d459eae0ad988681d70d6d150d35199479ea227/recipe/meta.yaml#L30

I noticed the `libgdal` conda-forge repo is archived. What does that mean for `rasterio`?

**Comment by ocefpaf** [comment]
The `libgdal` package still exist. Both `gdal` (python bindings) and `libgdal` the rest of the library, are in the `gdal` feedstock now.

**Comment by snowman2** [comment]
Good to know. Thanks for the update!
