### ISSUE TITLE
Most recent rebuild is not available for Windows

### ISSUE THREAD

**Issue by djhoese** [conda-forge/rasterio-feedstock#140]
Looks like the most recent rebuild of 1.0.25 was not successful for Windows. Could someone rerun it (assuming it was supposed to pass).

No files for the most recent build for win64:
https://anaconda.org/conda-forge/rasterio/files

Failed Windows builds:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=62473

**Comment by snowman2** [comment]
The GDAL 3 build failed for windows - we merged anyway to allow other OS to have support. GDAL 2.4 and PROJ 6 works for all OS.

**Comment by djhoese** [comment]
So it is impossible to have rasterio, proj 6+, pyproj 2.1+, and cartopy in one environment? That's what I'm seeing at least.

**Comment by snowman2** [comment]
It should work: https://github.com/conda-forge/rasterio-feedstock/pull/138

**Comment by djhoese** [comment]
On mobile now, but I think the builds from your PR are not being discovered. Perhaps cartopy is being built with only the new pinnings (the ones used in the rerender PR by @ocefpaf) and not the ones used in your PR.

**Comment by snowman2** [comment]
Looks like only the python 3.7 windows build worked (build 1) https://anaconda.org/conda-forge/rasterio/files

**Comment by djhoese** [comment]
Interesting, but I'm using python 3.7 so this shouldn't have mattered. I'll try to get a Windows machine running so I can get a better error message on what about the specification isn't possible. I'm currently running this on travis jobs.

**Comment by snowman2** [comment]
@ocefpaf, are you able to rerun the windows 3.6 build? [Build link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=62419)

**Comment by ocefpaf** [comment]
Done! Fingers crossed.

**Comment by snowman2** [comment]
🤞

**Comment by ocefpaf** [comment]
More details on https://github.com/conda-forge/rasterio-feedstock/pull/148#issuecomment-530980641 and https://github.com/conda-forge/rasterio-feedstock/pull/148#issuecomment-530981820. Meanwhile we are providing only `gdal 2.4` versions of `rasterio`.

PS: it would be nice to have a statement from upstream that it does work on `gdal 3.0` on Windows so we know it is something we have to fix.

**Comment by ocefpaf** [comment]
I guess we finally nailed these builds in #152
