### ISSUE TITLE
Is there a way to install rasterio with WEBP support? 

### ISSUE THREAD

**Issue by d3netxer** [conda-forge/rasterio-feedstock#154]
Is there a way to install rasterio with WEBP driver?

**Comment by ocefpaf** [comment]
The support is in the `gdal` library used to build `rasterio`. Do you have a minimal example case that we can try to reproduce?

**Comment by d3netxer** [comment]
@ocefpaf maybe you can take a look at how I am trying to install it?

```
conda create --name rasterio_w_webp_test1 python=3.7
 
conda config --add channels conda-forge
 
conda install gdal libgdal
 
conda install rasterio
 
pip install rio-cogeo
```

Then I am using the rio cogeo command that uses WebP:
```
rio cogeo create -p webp input.tif output.tif
```

but I get the following error:
```
File "rasterio/shutil.pyx", line 139, in rasterio.shutil.copy
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_AppDefinedError: Cannot create TIFF file due to missing codec for WEBP.
```

I don't understand. If I use the command 'gdalinfo --formats' I see WEBP as a format.

**Comment by xylar** [comment]
I was able to run your test command.  I already have `conda-forge` added to my channels and strict channel priority set.
```
$ conda create -y -n test python=3.7 gdal libgdal rasterio rio-cogeo boto3
$ conda activate test
$ rio cogeo create -p webp input.tif output.tif
/home/xylar/miniconda3/envs/test/lib/python3.7/site-packages/rio_cogeo/profiles.py:183: UserWarning: Non-standard compression schema: webp. The output COG might not be fully supported by software not build against latest libtiff.
  " supported by software not build against latest libtiff.".format(key)
Reading input: /home/xylar/Desktop/input.tif
Adding overviews...
Updating dataset tags...
Writing output to: /home/xylar/Desktop/output.tif
```
For my `input.tif`, I used https://github.com/mapbox/rasterio/blob/master/tests/data/cogeo.tif

I don't know enough about the expected result to know if my result was successful.  `eog` shows a blank file but that may be its limitation.

@d3netxer, could you let me know if this is still an ongoing issue for you or if it can be closed?
