### ISSUE TITLE
install instruction does not work

### ISSUE THREAD

**Issue by davidjohnson11** [conda-forge/rasterio-feedstock#159]
Issue:
Typing conda install rasterio into a Anaconda Powershell Prompt produces the following results:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

at this point I killed the whole thing with control-C because it had failed beyond that point previously.

Should I give up on Anaconda, rasterio or both?  Should I look elsewhere for a way to install this library?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
Please take a look at our docs and how to manage multiple channels. Also, if you don't fill the required information on the issue we cannot debug it. I'm closing this one so you can open a new one with the required info.
