### ISSUE TITLE
Please add support for arm64v8

### ISSUE THREAD

**Issue by robmarkcole** [conda-forge/rasterio-feedstock#197]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: I am on an M1 Mac and building a docker image based onarm64v8/python:3.8-slim. I wish to install via https://anaconda.org/conda-forge/rasterio but arm64v8 is not currently supported

**Comment by ocefpaf** [comment]
We need to do gdal first but that is already under way. I'll add fiona and rasterio to our migration to a PR will show up here eventually when all the dependencies are done.

**Comment by robmarkcole** [comment]
@ocefpaf thanks for the update

**Comment by xylar** [comment]
Addressed by #215
