### ISSUE TITLE
proj8.1 migration needs run for rasterio

### ISSUE THREAD

**Issue by akrherz** [conda-forge/rasterio-feedstock#218]
I believe the proj8.1 migration can be run for rasterio now?  I am unsure how to envoke this, so I kindly nudge @xylar about it.

**Comment by ocefpaf** [comment]
Working on it...

**Comment by ocefpaf** [comment]
Looks like the PR was not issued yet: https://conda-forge.org/status/#proj810 

We did merge https://github.com/conda-forge/gdal-feedstock/pull/533 yesterday so it is either coming or we need to check the gdal pin on rsaterio.

**Comment by akrherz** [comment]
Thanks for the response.

I believe GDAL 3.3 got done in #207, but it was manual vs the bot run in #211, which got closed.  Maybe that is at issue for future automation?

**Comment by xylar** [comment]
closed via #219
