### ISSUE TITLE
conda install fails with Python 3.9

### ISSUE THREAD

**Issue by andrea-bistacchi** [conda-forge/rasterio-feedstock#241]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hello, I cannot install with **conda** in a Python 3.9 freshly installed and updated environment (on Windows).

```
>> conda install -c conda-forge rasterio

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \

... and it runs forever ...
```

Note that on 3.8 it is OK.

Thanks very much!

### Installed packages

```shell
Python 3.9
```

### Environment info

```shell
clean environment just created
```

**Comment by xylar** [comment]
@andrea-bistacchi thanks for reporting.  We really do need the output about the environment to help you debug this.  A likely cause would be mixing the conda-forge and the defaults channels.

Can you try creating a new environment and installing rasterio at the same time?
```
conda create -n test -c conda-forge python=3.9 rasterio
```
You can include other packages along the way.

You should also strongly consider adding:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
This can help to prevent getting different packages from different channels.  See https://conda-forge.org/#about
