### ISSUE TITLE
Rasterio and libdap conflict over icu version

### ISSUE THREAD

**Issue by robintw** [conda-forge/rasterio-feedstock#26]
I've tried to install rasterio in a new environment by running:

`conda create -n test rasterio`

However, when I try to import rasterio I get the following:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/robin/anaconda3/envs/rr5/lib/python3.5/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import gdal_version
ImportError: dlopen(/Users/robin/anaconda3/envs/rr5/lib/python3.5/site-packages/rasterio/_base.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libicui18n.56.dylib
  Referenced from: /Users/robin/anaconda3/envs/rr5/lib/libgdal.20.dylib
  Reason: image not found
```

It seems that rasterio requires version 56 of ICU, however if I force install that version (`conda install icu=56`), then I get an error from `libdap` which seems to require version 58:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/robin/anaconda3/envs/rr6/lib/python2.7/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import gdal_version
ImportError: dlopen(/Users/robin/anaconda3/envs/rr6/lib/python2.7/site-packages/rasterio/_base.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/robin/anaconda3/envs/rr6/lib//libdap.23.dylib
  Reason: image not found
```

Any ideas on what I can do to resolve this?

**Comment by ocefpaf** [comment]
Due the the Travis-CI outage we are behind the with the re-pinning from `icu 56.*` to `icu 58.*`. I just merged `gdal` and as soon as that makes into the channel I will re-build `fiona` and `rasterio`. Should be fixed before the end of the day.

The work around for now is to force `icu 56.*` and `libxml2 2.9.3` into your env. (untested!)
