### ISSUE TITLE
Build on `main` failed

### ISSUE THREAD

**Issue by zklaus** [conda-forge/rasterio-feedstock#270]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The latest build on `main`, I think simply due to some network quirk in one osx build. @conda-forge/rasterio, could somebody restart the build please?

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by ocefpaf** [comment]
I restarted it. Let's hope that is enough.

**Comment by zklaus** [comment]
Seems to have done the trick. Thanks, @ocefpaf!
