### ISSUE TITLE
Change dependency from libgdal to libgdal-core or gdal

### ISSUE THREAD

**Issue by theroggy** [conda-forge/rasterio-feedstock#303]
### Comment:

The GDAL conda package has recently been revamped to seperate the core functionalities and a list of optional dependencies. It would be great if rasterio users could have the advantages of this as well.

In practice a new `libgdal-core` package has been introduced, as well as a list of seperate packages with optional plugins. The old `libgdal` depends on all the new packages to have backwards compatibility.

The following optional GDAL dependencies were moved to seperate conda packages (reference https://github.com/conda-forge/gdal-feedstock/issues/722#issuecomment-2204537063):

- libgdal-arrow-parquet (arrow dependency)
- libgdal-jp2openjpeg (openjpeg dependency)
- libgdal-pdf (poppler dependency)
- libgdal-postgisraster (postgresql dependency)
- libgdal-pg (postgresql dependency)
- libgdal-fits (cfitsio dependency)
- libgdal-xls (freexls dependency)
- libgdal-grib (libaec dependency)
- libgdal-kea (kealib dependency)
- libgdal-tiledb (tiledb dependency)
- libgdal-netcd (libnetcdf dependency)
- libgdal-hdf4 (hdf4 dependency)
- libgdal-hdf5 (hdf5 dependency)

If a user wants to read a file where one of these dependencies is needed but unavailable, they will get a clean error, and just have to install the appropriate extra package to get it working.

An important thing to note is that the new `libgdal-core` package is only available for GDAL 3.9.1 at this time. Unless I'm mistaken, this would lead to new versions of rasterio to only be installable with GDAL 3.9.1?

An alternative to avoid this could be to depend on the `gdal` package. This is the package that includes the GDAL python bindings, but the advantage is that for older versions this depends on `libgdal` and starting from 3.9.1 it depends on `libgdal-core`. This way it stays possible to install with an old GDAL.

I recently opened a similar issue for pyogrio: https://github.com/conda-forge/pyogrio-feedstock/issues/48

**Comment by weiji14** [comment]
+1 from me for changing to `libgdal-core`, but maybe we should wait for rasterio 1.4.0 instead of doing it now in 1.3.10?

> An important thing to note is that the new `libgdal-core` package is only available for GDAL 3.9.1 at this time. Unless I'm mistaken, this would lead to new versions of rasterio to only be installable with GDAL 3.9.1?

This is already the case with new versions of rasterio since https://github.com/conda-forge/rasterio-feedstock/pull/301. We follow conda-forge's global GDAL pinnings here which is already on 3.9.x.

**Comment by omad** [comment]
This would be extremely welcome here too. Not pulling in everything would be amazing.

More information on the change is available in this Quansight blog post: [Introducing Lightweight Versions of GDAL and PDAL](https://quansight.com/post/introducing-lightweight-versions-of-gdal-and-pdal/)

**Comment by weiji14** [comment]
Yep, the first beta 1.4 release of rasterio was just out yesterday (https://github.com/rasterio/rasterio/releases/tag/1.4b1), so hopefully we can switch to `libgdal-core` soon!

**Comment by theroggy** [comment]
Not important, but to be clear...

The difference is minimal, so I don't mind at all, but the dependency change in #316 is to `gdal`, while I interpreted the exchange here to have landed on `libgdal-core`.

**Comment by akrherz** [comment]
Hi @theroggy , first a check on linux64

cmd | env size
--- | ---
`mamba create -n dev python=3.12 rasterio=1.4.0` | 77MB
`mamba create -n dev python=3.12 rasterio=1.3.11` | 111MB

That looks better... I suppose the question is if rasterio actually imports gdal's python bindings?  I'll PR a test now

**Comment by theroggy** [comment]
@akrherz 
> first a check on linux64

Interesting... on windows:

cmd | env size
-- | --
mamba create -n dev python=3.12 rasterio=1.4.0 | 1.04 GB
mamba create -n dev python=3.12 rasterio=1.3.11 | 1.88 GB

**Comment by weiji14** [comment]
For future reference, definitely stick with libgdal(-core) instead of gdal, see rasterio docs - https://github.com/rasterio/rasterio/blob/1.4.0/docs/topics/switch.rst#mutual-incompatibilities

**Comment by akrherz** [comment]
Thanks, I did some review if there is any chance of installing `rasterio=1.4.0` and `gdal<3.9` and the answer appears to be no with all the various tight pinning that rightfully happens in this space.
