### ISSUE TITLE
Bringing back rasterio dev builds

### ISSUE THREAD

**Issue by sgillies** [conda-forge/rasterio-feedstock#306]
Rasterio is going to have a 1.4.0rc1 soon. Is the approach @xylar took at https://github.com/conda-forge/fiona-feedstock/pull/227#issuecomment-2259896103 the way to go?

**Comment by akrherz** [comment]
I think that was just a one-time update needed to bring `dev` branch back to something resembling `main`.

**Comment by sgillies** [comment]
@akrherz the `dev` branch here is 459 commits behind main, so I assumed something similar would be needed?

**Comment by akrherz** [comment]
So sorry, I see what you are saying now and yes, that seems logical.

**Comment by ocefpaf** [comment]
In conda-forge we never separated the boilerplate build configuration, that is handled by `conda-forge.yml` and `conda_build_config.yaml` from the recipe. That makes all those commits look scary but in reality they are are auto-generated by conda-smithy.

The TL;DR is that we can:
- remove the current dev branch
- start a fresh one from main
- port only the necessary changes from those two files and re-render

I can do that in a sec...

**Comment by akrherz** [comment]
I am unsure what is happening, but `dev` branch did not appear to attempt to build after #307 was merged.  I will push an empty commit to see if I can wake it up

**Comment by akrherz** [comment]
That seemed to work, :eyes: https://github.com/conda-forge/rasterio-feedstock/runs/28784381102

**Comment by sgillies** [comment]
Thanks @akrherz ! I'm updating rasterio_dev to 1.4.0rc2 now in #313
