### ISSUE TITLE
bump to 1.0a10?

### ISSUE THREAD

**Issue by rsignell-usgs** [conda-forge/rasterio-feedstock#42]
@ocefpaf, I was going to submit a PR to bump to 1.0a10, but looking at this:
https://github.com/conda-forge/rasterio-feedstock/commit/21dc55d8a6a7c1c61ddf15055eacf0ff2af87dee#diff-e178b687b10a71a3348107ae3154e44c
I wasn't sure if that was a good idea.

**Comment by ocefpaf** [comment]
Rich, we have a dev branch with the alpha version. You can install the latest alpha with  '-c conda-forge/dev'

**Comment by ocefpaf** [comment]
@rsignell-usgs I typed that on my phone and got it all wrong. The right command to get the `dev` version of `rasterio` is:

```shell
conda install rasterio -c conda-forge/label/dev
```
