### ISSUE TITLE
libpoppler.so.66: cannot open shared object file

### ISSUE THREAD

**Issue by shoyer** [conda-forge/rasterio-feedstock#49]
We build our docs for xarray with rasterio from the conda-forge channel. The latest doc build I tried failed, apparently due to an issue with rasterio and/or libpoppler:
```
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/doc-fix-dask/doc/gallery/plot_rasterio.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/doc-fix-dask/doc/gallery/plot_rasterio.py", line 25, in <module>
    from rasterio.warp import transform
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/doc-fix-dask/lib/python3.5/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libpoppler.so.66: cannot open shared object file: No such file or directory
```

See https://readthedocs.org/projects/xray/builds/6330741/ for full details on this build.

This looks similar to https://github.com/conda-forge/fiona-feedstock/issues/62, so my guess is that we may simply need to rebuild another version of the rasterio package? @ocefpaf any good suggestions here?

**Comment by ocefpaf** [comment]
> @ocefpaf any good suggestions here?

Yep. Rebuild is the solution. I'm working on that and it should be finished later today early tomorrow.

**Comment by shoyer** [comment]
Thanks!

**Comment by ocefpaf** [comment]
@shoyer I checked and the new `gdal` builds are already in the channel, so maybe this is something else.

I am assuming that the env file used is [this one](https://github.com/pydata/xarray/blob/master/doc/environment.yml), correct?

If so can you try to modify it to:

```yaml
name: xarray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy=1.11.2
  - pandas=0.20.1
  - numpydoc=0.6.0
  - matplotlib=2.0.0
  - seaborn=0.8
  - dask=0.12.0
  - ipython=5.1.0
  - sphinx=1.5
  - netCDF4=1.3.1  # 1.2.9 was built with hdf 1.8.18 and causes many undesirable downgrades.
  - cartopy=0.15.1
  - rasterio=1  # I guess that this version is needed for `open_rasterio`
  - sphinx-gallery  # conda-forge has sphinx-gallery ;-)
```

That should get you the correct version of `gdal` that uses `hdf5 1.10.1` (and latest `poppler` and fixes the `rasterio` failure you are seeing).

If you really need `netcdf4 1.2.9` we would need to rebuild that version with `hdf5 1.10.1`.

**Comment by shoyer** [comment]
Yes, updating netcdf4 fixed it. Thanks!

**Comment by ocefpaf** [comment]
No problem. If you do need older version and/or other dependency combinations for testing let me know and we can add them to the channel.
