### ISSUE TITLE
Rasterio and GDAL 1.11.4

### ISSUE THREAD

**Issue by fmaussion** [conda-forge/rasterio-feedstock#5]
Folks,

our CI is broken since at least a couple of days (I don't know when exactly). Note that in a fresh environment, the following works fine:

```
conda install -c conda-forge rasterio
```

However our install script is following (sorry for the lengthy list):

```
conda install -c conda-forge geopandas matplotlib Pillow joblib netCDF4 scikit-image configobj nose pyproj numpy krb5 rasterio xarray
```

This has the effect to downgrade gdal: `1.11.4-np111py35_5 --> 1.11.4-np111py35_4`

And then I get the following error on linux (on other platforms the message might be different):

```python
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mowglie/.bin/conda/envs/test_rasterio/lib/python3.5/site-packages/rasterio/__init__.py", line 7, in <module>
    from rasterio._base import (
ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory
```

Any clue what's going on?

**Comment by ocefpaf** [comment]
`gdal 1.11.4-np111py35_5` is compiled against `jpeg 9b` while `gdal 1.11.4-np111py35_4` is compiled against `jpeg 8d`. Not sure why you are getting downgraded there... A workaround is to install `jpeg 8d`.

**Comment by fmaussion** [comment]
I was suspecting `fiona`, but you are the expert here ;-)

**Comment by ocefpaf** [comment]
Sorry, I spoke too soon. Both `gdal` `_4` and `_5` are compiled against `jpeg 9b`. It seems that `scikit-image` is the culprit for downgrading to `jpeg 8b` (and `gdal` `_4` **is** compiled against `jpeg 9d` but not pinned to it.)

Try adding `jpeg=9b` to the end of your install list. Not sure if `scikit-image` will work with that jpeg though.

**Comment by fmaussion** [comment]
Thanks for your help. It aborts with dependency issues: 

```
$ conda install -c conda-forge geopandas matplotlib Pillow joblib netCDF4 scikit-image configobj nose pyproj numpy krb5 rasterio xarray jpeg=9b
Fetching package metadata: ......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - gdal (target=gdal-1.11.4-np110py34_4.tar.bz2) -> hdf4
  - gdal (target=gdal-1.11.4-np110py34_4.tar.bz2) -> jpeg *|9*
  - gdal (target=gdal-1.11.4-np110py34_4.tar.bz2) -> python 2.7*|3.5*
  - geopandas -> gdal 1.11.4|==1.11.4
  - geopandas -> python 2.7*|3.5*
  - hdf4 (target=hdf4-4.2.11-0.tar.bz2) -> jpeg *|9*|9b
  - jasper (target=jasper-1.900.1-1.tar.bz2) -> jpeg *|9b
  - jpeg 9b*
  - pillow -> freetype 2.4*
  - pillow -> jpeg 8*|8d
  - pillow -> python 2.7*|3.5*
  - scikit-image -> pillow
  - scikit-image -> python 2.7*|3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ocefpaf** [comment]
Argh... Pillow is also compiled against `jpeg 8b`... It seems that we either have to re-release `gdal` with an older `jpeg` or upgrade a bunch of Software...

**Comment by fmaussion** [comment]
sorry for the dependency spaghetti... Our project is just using whatever is available, I am starting to see that this was not the best choice...

**Comment by ocefpaf** [comment]
No need to be sorry. The Software version pinning in conda is not ideal yet. I will ping you here once we have a way forward. Hold on...

**Comment by fmaussion** [comment]
@ocefpaf , just to let you know that the build triggered last night were successful: https://travis-ci.org/OGGM/oggm

What did change between yesterday and today?

**Comment by ocefpaf** [comment]
> What changed between yesterday and today?

I forgot to ping you here. I triggered a rebuild of the whole stack with the proper versions.

Virtually all of `conda-forge` packages are using `jpeg 9b`, so you might still find broken things when mixing packages from the default channel that uses `jpeg 8d`.

**Comment by fmaussion** [comment]
Perfect, thanks so much! 

We now advise our users to use conda-forge as default channel ;-) http://oggm.readthedocs.org/en/latest/installing-oggm.html#packages

**Comment by ocefpaf** [comment]
Off-topic: I just checked https://github.com/OGGM/oggm. Cool project! I am happy to know that some of my work here is helpful there. I started my life as an oceanographer trying to study ocean-ice interface. Since I am from Brazil you can see that I had to change the subject of my research :wink:
