### ISSUE TITLE
installing rasterio >1.0a11 requiring gdal 2.2.*

### ISSUE THREAD

**Issue by jdmcbr** [conda-forge/rasterio-feedstock#51]
gdal 2.2.* is still incompatible with `fiona` (and #41 was closed for that reason), but the recipes for 1.0a11 and 1.0a12 require updating to gdal 2.2.*. Is there any way around that? I'm guessing no, based on #46, but just wanted to make sure.

**Comment by ocefpaf** [comment]
We can bump the build number and add a version with `gdal 2.1` if you want, but the next version of `fiona` will work with `gdal 2.2.*` and a release is near, so I don't really want to send PRs to do that :grimacing: But I will review and merge a PR if you are willing to :wink:
