### ISSUE TITLE
libgdal instead of gdal?

### ISSUE THREAD

**Issue by snowman2** [conda-forge/rasterio-feedstock#64]
Should the rasterio recipe use libgdal instead of gdal as the gdal python bindings are not necessary?

**Comment by ocefpaf** [comment]
I recall testing but I do not recall the results (if python bindings are needed or not). Do you want to try that again?

**Comment by snowman2** [comment]
They are not necessary. In the [environment.yml](https://github.com/mapbox/rasterio/blob/master/environment.yml) in the repository it only has libgdal listed. I also tested it locally and ran all of the tests and it worked. Is this something to modify in PR #65? Or would you prefer a separate PR?

**Comment by ocefpaf** [comment]
You can use #65 no need for a separate PR.

**Comment by snowman2** [comment]
Okay. Will add that to the PR then.

**Comment by ocefpaf** [comment]
Done in #63
