### ISSUE TITLE
Is Rasterio's Numpy requirement correctly specified?

### ISSUE THREAD

**Issue by sgillies** [conda-forge/rasterio-feedstock#7]
Hi! A colleague of mine reported that the Rasterio 0.34 package was broken w/re Miniconda2 yesterday because of a Numpy version mismatch, but trying it today, I find that it's fine. I wonder if installing the conda-forge Rasterio package always upgrades Numpy to the required version or not?

Can you explain to me how the Numpy requirement at https://github.com/conda-forge/rasterio-feedstock/blob/master/recipe/meta.yaml#L29 works? If the Rasterio package was built using Numpy 1.11 headers, does a user get upgraded to 1.11 when they install Rasterio?

**Comment by ocefpaf** [comment]
Hi @sgillies nice that conda-foge is in your radar!

> Can you explain to me how the Numpy requirement at https://github.com/conda-forge/rasterio-feedstock/blob/master/recipe/meta.yaml#L29 works? If the Rasterio package was built using Numpy 1.11 headers, does a user get upgraded to 1.11 when they install Rasterio?

Exactly. The `numpy x.x` ensures that the numpy version used to build the package is baked in the build string. That ensures the right `numpy` will always installed alongside the right `rasterio` build. For example `rasterio 0.34.0 np110py35_1` will download/update/downgrade to `numpy 1.10`.

However, the default channel does the same thing! That problem should not happen there. To debug this properly we need to know the output of `conda list` with the show channel option turn on.

Note that I could not find `rasterio 0.34` in the default channel. See http://anaconda.org/anaconda/rasterio/files. I think that your colleague might have got that package from another channel.

PS: Would you like to be added as a maintainer of the `rasterio` and `fiona` recipes here in conda-forge :grin: ?

**Comment by sgillies** [comment]
Thanks for the debugging advice. I'll look into that.

I'm going to pass on being a maintainer for now because I'm not a conda user, but I'll watch the repos and contribute bug reports and patches, for sure.

**Comment by ocefpaf** [comment]
> I'm going to pass on being a maintainer for now because I'm not a conda user, but I'll watch the repos and contribute bug reports and patches, for sure.

If you change your mind just send a PR adding your GitHub handle here https://github.com/conda-forge/rasterio-feedstock/blob/master/recipe/meta.yaml#L45-L48. That will give you commit rights to this repository.

The maintainer job is easy: update the recipe with new releases, and merge the occasional maintenance PR. I am happy to answer any questions you might have.
