### ISSUE TITLE
Potentially need to revisit tests skipped?

### ISSUE THREAD

**Issue by snowman2** [conda-forge/rasterio-feedstock#93]
https://github.com/conda-forge/rasterio-feedstock/blob/b4d204dd8f9367d580e300e88f25c60a933058bd/recipe/meta.yaml#L58

**Comment by snowman2** [comment]
It was a note to take a look at later. They might be okay, but some tests have been added and I was thinking it would be a good idea to see if any of the new tests should be skipped.

**Comment by sgillies** [comment]
Fwiw, here's the command that's run when I test the rasterio wheels that go to PyPI: 

`python -m pytest -vv tests -m "not gdalbin" -k "not test_ensure_env_decorator_sets_gdal_data_prefix"`

https://github.com/sgillies/rasterio-wheels/blob/master/config.sh#L258

There are a number of tests that will only pass for the wheels and I've added a custom mark. The rasterio-feedstock should use `-m "not wheel"`. Sorry I didn't speak up about this sooner! I'll follow up in the fiona-feedstock project.

**Comment by snowman2** [comment]
Thanks for the info @sgillies, I made an attempt to update the test command for issue #92. If you see something that should be updated, feel free to make comments. Thanks!
